# Generated by Django 3.0.5 on 2022-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20220715_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tim_kiem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tim_kiem_id', models.SmallIntegerField()),
                ('ten_tim_kiem', models.CharField(blank=True, max_length=100, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('chuoi_tim_kiem', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
