# Generated by Django 3.0.5 on 2022-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_tim_kiem'),
    ]

    operations = [
    #     migrations.RemoveField(
    #         model_name='mon_hoc',
    #         name='ma_khoi',
    #     ),
    #     migrations.RemoveField(
    #         model_name='mon_hoc',
    #         name='ma_mon',
    #     ),
    #     migrations.RemoveField(
    #         model_name='mon_hoc',
    #         name='mon_tit',
    #     ),
    #     migrations.RemoveField(
    #         model_name='mon_hoc',
    #         name='ten_mon',
    #     ),
        # migrations.AlterField(
        #     model_name='studentextra',
        #     name='roll',
        #     field=models.CharField(max_length=10, null=True),
        # ),
    ]
