# Generated by Django 3.0.5 on 2022-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20220716_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mon_hoc',
            name='ma_mon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mon_hoc',
            name='ten_mon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='roll',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
